# Generated by Django 4.0 on 2023-02-15 17:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='passenger',
            field=models.ManyToManyField(blank=True, null=True, related_name='pas', to=settings.AUTH_USER_MODEL),
        ),
    ]
